name: 功能工单
description: 提供一个功能请求工单，以便添加新功能。
labels: ["Template: Feature Request"]
body:

  - type: markdown
    attributes:
      value: |
        功能工单需要时间进行评估和开发。请确保你的功能请求是有意义的，并且符合项目的目标。

  - type: textarea
    attributes:
      label: 提交的功能将会解决什么问题？请描述。
      description: 简单描述你所需的功能。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 描述你想要实现的功能
      description: 简单描述你想要实现的功能。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 描述你所考虑的任何替代解决方案或功能
      description: 简单描述你所考虑的任何替代解决方案或功能。

  - type: textarea
    attributes:
      label: 其他信息
      description: 添加任何其他信息或屏幕截图。
