name: 错误工单
description: 创建一个错误描述工单用于修复固件。
labels: ["Template: Bug"]
body:

  - type: markdown
    attributes:
      value: |
        # 请填写所有必须的字段

  - type: textarea
    attributes:
      label: BUG描述
      description: 请描述BUG的现象。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现步骤
      description: 请描述如何复现BUG。
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # 设置/版本信息

  - type: input
    attributes:
      label: 飞控型号
      description: 填写飞控型号。
      placeholder: |
          Hummingbird F4 Pro
      render: txt
    validations:
      required: true

  - type: input
    attributes:
      label: 固件版本
      description: 填写Betaflight版本号（最好附带固件末尾的哈希码 - 如 xxx_a788wf77.hex）。
      placeholder: |
          4.5.1 或 4.5.1_a788wf77
      render: txt
    validations:
      required: true

  - type: textarea
    attributes:
      label: 外设信息
      description: 如果有关外设BUG，填写外设的信息 (接收机, VTX, 品牌/型号, 外设的固件版本等)。

  - type: textarea
    attributes:
      label: 外设连接方式
      description: 如 I2C1/UART2，连接到引脚 PA0/PC3 等。

  - type: markdown
    attributes:
      value: |
        # 其他信息

  - type: textarea
    attributes:
      label: 需要补充的信息
